---
title: "Tabla de Datos"
format: html
editor: visual
theme: lux
---

En caso de una consulta más detallada, visitar la información brindada por el [DANE](https://microdatos.dane.gov.co/index.php/catalog/833)

Se muestran las variables originales con sus respectivas clasificaciones:


::: panel-tabset

### Diccionario de Variables

## Variables Originales

| **Identificador** | **Descripción**                                                                               |
|-------------------|-----------------------------------------------------------------------------------------------|
| CORRELA_16        | Clasificación CIIU.                                                                           |
| CORRE_9           | Grupo CIIU.                                                                                   |
| IDOJI             | Organización jurídica.                                                                        |
| IDAIO             | Año de inicio de operaciones.                                                                 |
| REGALA            | Regalías causadas.                                                                            |
| OUTSOURCING       | Costos y gastos por servicios contratados con terceros (outsoursing).                         |
| PERREMUN          | Personal remunerado.                                                                          |
| SOCIOS            | Propietarios, socios y familiares. Total sin remuneración.                                    |
| PERSONOM          | Total de personal permanente.                                                                 |
| DIRECTO           | Total de personal temporal contratado de manera directa.                                      |
| AGENCIA           | Total de personal temporal contratado a través de agencias.                                   |
| APRENDIZ          | Total de aprendices.                                                                          |
| TOTPERSO          | Total de personal.                                                                            |
| PROMUJ            | Total de mujeres propietarias y socias.                                                       |
| PROHOM            | Total de hombres propietarios y socios.                                                       |
| PERMUJ            | Total de mujeres que sean personal permanente.                                                |
| PERHOM            | Total de hombres que sean personal permanente.                                                |
| DIRMUJ            | Total de mujeres que sean personal temporal contratadas de manera directa.                    |
| DIRHOM            | TOtal de hombres que sean personal temporal contratados de manera directa.                    |
| AGEMUJ            | Total de mujeres en personal temporal contratadas a través de agencias.                       |
| AGEHOM            | Total de hombres en personal temporal contratados a través de agencias.                       |
| APRENMUJ          | Número de aprendices mujeres.                                                                 |
| APRENHOM          | Número de aprendices hombres.                                                                 |
| TOTMUJ            | Personal de mujeres total.                                                                    |
| TOTHOM            | Personal de hombres total.                                                                    |
| CIMREP            | Costo de insumos respecto a ingresos por ventas.                                              |
| BRUTA             | Producción bruta de la empresa.                                                               |
| CONSUI            | Consumo intermedio entre 1996 y 2006.                                                         |
| GAS               | Gasto en gas natural.                                                                         |
| EMPAQUE           | Gasto en Empaques y embalajes.                                                                |
| HONORA            | Gasto en Honorarios y servicios técnicos.                                                     |
| COMISION          | Gastos de ventas por comisión a terceros.                                                     |
| ARRIENDO          | Gasto en Arrendamiento de bienes inmuebles y muebles.                                         |
| SEGURO            | Gasto en Seguros,excepto los de prestaciones.                                                 |
| ASEO              | Gasto en Aseo y vigilancia.                                                                   |
| ENERGIA           | Gasto en Energía eléctrica comprada.                                                          |
| COMUNICA          | Gasto en Comunicaciones.                                                                      |
| PUBLICO           | Gasto en Otros servicios públicos.                                                            |
| FLETES            | Gasto en Transporte, fletes y acarreos.                                                       |
| PUBLICI           | Gasto en Propaganda y publicidad.                                                             |
| ADECUA            | Gasto en Mantenimiento, reparaciones.                                                         |
| OTROS             | Otros gastos inherentes a la actividad comercial.                                             |
| SUELDOS           | Total de sueldos y salarios causados en el año.                                               |
| PRESTAC           | Total en prestaciones sociales causadas en el año.                                            |
| VENTA             | Ventas causadas en el año.                                                                    |
| AGREGA            | Valor Agregado.                                                                               |
| SUEPLAN           | Sueldos de planta.                                                                            |
| PREPLAN           | Prestaciones de planta.                                                                       |
| REMPLAN           | Remuneración de planta.                                                                       |
| COTIZA            | Cotizaciones patronales obligatorias causadas en el año.                                      |
| RENTEMP           | Gastos causados por el personal temporal suministrado por agencias de empleo.                 |
| TOTREM            | Total en Remuneración.                                                                        |
| INVINI            | Valor en Existencias desde el 31 de diciembre de 2005.                                        |
| INVFIN            | Valor en Existencias desde el 31 de diciembre de 2006.                                        |
| ROTACION          | Rotación de Inventarios.                                                                      |
| INVPRO            | Inventario Promedio.                                                                          |
| CTO               | Costo de mercancia vendida.                                                                   |
| CTOINS            | Total costo de la mercancía más costo de insumos de actividades relacionadas con el comercio. |
| GASTOS            | Total costos y gastos operacionales.                                                          |
| GASTOSNOP         | Subtotal Gastos no operacionales.                                                             |



Porterior a la limpieza, clasificaremos los datos en 2 tipos de variables (discretas y continuas). Buscaremos variables que sean de nuestro interes, y que ademas no sean combinacion lineal de otras. Algunas variables con gran cantidad de ceros, seran clasificadas como variables discretas.

### Cualitativas

| **Identificador** | **Descripción**                                                                               |
|-------------------|-----------------------------------------------------------------------------------------------|
| CORRELA_16        | Clasificación CIIU.                                                                           |
| IDOJI             | Organización jurídica.                                                                        |
| IDAIO             | Edad de la Empresa                                                                            |
| PROMUJ            | La empresa cuenta con mujeres propietarias y socias.                                          |
| PERMUJ            | Porcentaje de mujeres como personal permanente.                                               |
| PERHOM            | Porcentaje de hombres como personal permanente.                                               |
| DIRMUJ            | Porcentaje de mujeres como personal contratado de manera directa.                             |
| DIRHOM            | Porcentaje de hombres como personal contratado de manera directa.                             |
| AGENCIA           | Porcentaje de mujeres y hombres contratados por medio de agencia.                             |
| APRENMUJ          | Porcentaje de mujeres aprendices.                                                             |
| APRENHOM          | Porcentaje de hombres aprendices.                                                             |
| PUBLICI           | Gasto en publicidad relativo a producción bruta.                                              |
| TMÑEMP            | Tamaño de la empresa.                                                                         |



### Cuantitativas

| **Identificador** | **Descripción**                                                                               |
|-------------------|-----------------------------------------------------------------------------------------------|
| BRUTA             | Producción bruta de la empresa.                                                               |
| CONSUI            | Consumo intermedio entre 1996 y 2006.                                                         |
| SUELDOS           | Total de sueldos y salarios causados en el año.                                               |
| PRESTAC           | Total en prestaciones sociales causadas en el año.                                            |
| VENTA             | Ventas causadas en el año.                                                                    |
| AGREGA            | Valor Agregado.                                                                               |
| SUEPLAN           | Sueldos de planta.                                                                            |
| PREPLAN           | Prestaciones de planta.                                                                       |
| COTIZA            | Cotizaciones patronales obligatorias causadas en el año.                                      |
| TOTREM            | Total en Remuneración.                                                                        |
| ROTACION          | Rotación de Inventarios.                                                                      |
| INVPRO            | Inventario Promedio.                                                                          |
| CTO               | Costo de mercancia vendida.                                                                   |
| CTOINS            | Total costo de la mercancía más costo de insumos de actividades relacionadas con el comercio. |
| GASTOS            | Total costos y gastos operacionales.                                                          |
| GASTOSNOP         | Subtotal Gastos no operacionales.                                                             |

:::


